### ISSUE TITLE
Ошибка! Пользователь заблокирован (cavia_porcellus)

### ISSUE THREAD

**Issue by ektova** [maxcom/lorsource#1000]
Hi. 
Почему меня заблокировали на лоре? :(

**Comment by xaizek** [comment]
Тебя никто не блокировал. Может баг какой-то.

**Comment by maxcom** [comment]
Блокировка на учетке не стоит. Напиши мне лучше в почту, восстановим доступ.

**Comment by yurikoles** [comment]
1k get ;)
