### ISSUE TITLE
У модератора нет кнопки разблокировки в профиле забаненного пользователя

### ISSUE THREAD

**Issue by Pinkbyte** [maxcom/lorsource#1012]
Сабж.

Используемая тема - black(пробовал переключить на tango - результат не изменился).

Браузер - Firefox 91.13.0

Смотрел как на профили забаненных мною пользователей, так и на забаненных другими модераторами - результат одинаковый, кнопки нет.

Пробовал смотреть в код сам, ничего толком не понял.

Заметил это сегодня(04.09.2022), но возможно проблема возникла и раньше - я как-то давненько не пробовал кого-то разбанивать :-/

Update: у замороженных(но не забаненных) пользователей обе формы(заморозки и бана) присутствуют как надо. У обычных пользователей(незамороженных И незабаненных) - тоже.

**Comment by Pinkbyte** [comment]
Update #2: судя по истории коммитов, ближайшее изменение в коде было в d6fc66211e59b685a9001367eada0ac1bd8cf7ea, если я конечно правильно всё понял

**Comment by maxcom** [comment]
Фикс выложил, проверь plz

**Comment by Pinkbyte** [comment]
Да, всё работает, спасибо
