### ISSUE TITLE
Ошибка! Пользователь "<invalid name>" не существует

### ISSUE THREAD

**Issue by zowers** [maxcom/lorsource#1017]
Пытаюсь восстановить пароль старого эккаунта, приходит код восстановления, но `/reset-password` фейлится с ошибкой
`Ошибка! Пользователь "<invalid name>" не существует`

**Comment by maxcom** [comment]
Нужен email или имя учетки.

**Comment by zowers** [comment]
как выяснилось на `/reset-password` нужно вводить имя а не email.
спасибо @maxcom
