### ISSUE TITLE
CVE :)

### ISSUE THREAD

**Issue by blogdron** [maxcom/lorsource#1062]
Не на ЛОРе :), извиняюсь за кликбейт, а в моём посте, **меня фрактал забанил** поэтому могу писать только тут.
 Можно удалить пост?
 * https://www.linux.org.ru/forum/talks/17116285

Я там в реализациях переводилки **перепутал кавычки** и у людей может случайно рм рф исполнится когда 
они копипастят текст из интернетов и переводят его. 
Как в коде из шапки, так и в коде из нижнего поста с обновлением. 
Поэтому прошу снести весь пост. **Пожавуста**  Отредактировать уже ничего нельзя :( А человекам вредить нихочу

----

Если в шапке корректоров можно попросить, то в сообщении не проправить уже, удолите от греха подальше. Спасибо. Извинити :(

**Comment by maxcom** [comment]
Я его прикрепил, теперь по идее должна быть доступна правка поста. Исправь
и напиши мне, когда можно будет открепить.

вт, 23 янв. 2024 г. в 12:07, BLOGDRON ***@***.***>:

**Comment by blogdron** [comment]
Хорошо, сейчас поправлю шапку спасибо ^.^

Но сообщение тогда вот это

* https://www.linux.org.ru/forum/talks/17116285?cid=17446482 удали пожалуйста всё же.  Его я не поправлю, а бага перекочевала и туда тоже. Спасибо.

Сейчас всё ещё раз перепроверю, исправлю и отпишусь как закончу.

**Comment by blogdron** [comment]
@maxcom всё сделал, спасибо большое ^.^. Блин кавычки эти, надо быть внимательнее...
