### ISSUE TITLE
Перерегистрация

### ISSUE THREAD

**Issue by h1dyg0at** [maxcom/lorsource#1088]
Добрый день, создал сегодня аккаунт "h1dyg0at" что читается как "ХайдиГОАТ", где "g0at" - это Great Of All Time. Ничего запретного здесь нет. Я получил бан.
Ознакомившись с правилами регистрации, я бы хотел изменить псевдоним на hidygoat, чтобы впредь не нарушать правила сообщества.

**Comment by maxcom** [comment]
Готово. Заходи по своему email'у или как "hidygoat", пароль не менялся.
