### ISSUE TITLE
whois: добавить ссылку на wiki

### ISSUE THREAD

**Issue by maxcom** [maxcom/lorsource#216]
Добавить в профиль пользователя на основном сайте (в whois) ссылку на страничку пользоватя wiki (User:xxx), страничку вклада. Хорошо бы эти ссылки показывать у всех, а только у тех у кого они существуют. Хорошо бы туда еще добавить какую-нибудь статистику из wiki вроде числа правок

(извлечено из #55)

**Comment by Pinkbyte** [comment]
Вики - всё :-(. Закрываем?
