### ISSUE TITLE
Опция для вкючения https постоянно

### ISSUE THREAD

**Issue by yurikoles** [maxcom/lorsource#260]
Так сделано на ФСБук, на других сайтах вообще все сидят через https. Обоснование это отсутствие http:// в адресной строке большинства современных браузеров, т.е. необходимость вводить https:// полностью.

**Comment by jollheef** [comment]
Не выглядит актуальным.

Задачу бы утилизировать.

**Comment by Pinkbyte** [comment]
HSTS сервер отдаёт, отдельная опция действительно не нужна, плюсую закрытие задачи
