### ISSUE TITLE
java.lang.ClassCastException: org.apache.struts.upload.MultipartRequestWrapper cannot be cast to javax.servlet.ServletRequestWrapper

### ISSUE THREAD

**Issue by ghost** [maxcom/lorsource#326]
when i am trying to migrate my application from sun server to jboss 6 it is creating the exception

environment:

struts
jsp

java.lang.ClassCastException: org.apache.struts.upload.MultipartRequestWrapper cannot be cast to javax.servlet.ServletRequestWrapper

for uploading i am using <input type="file" name="invoiceFile"> .

any one have idea.

Thanks in advace.

**Comment by icsraj** [comment]
Is there any update on this how the issue got resolved
