### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by lambdaterm** [maxcom/lorsource#605]
- пробуем добавить новую тему в любой раздел
- заполняем заголовок, тело сообщения, метки
- тыкаем "Предпросмотр"

> > Пишите осмысленный заголовок. Придумайте осмысленный заголовок теме. Сообщения с бессмысленными загловками ("Помогите!", "Вопрос", ...), как правило, остаются без ответа.
> 
> загловками

**Comment by Pinkbyte** [comment]
Пользователи негодуют - https://www.linux.org.ru/forum/linux-org-ru/11325239

**Comment by kloun** [comment]
@maxcom чего этот багрепорт открыт до сих пор?

**Comment by maxcom** [comment]
у этих текстов в БД нет редактора. Надо или редактор приделать, или перенести их в исходники чтобы править в интерфейсе github

**Comment by kloun** [comment]
я за второй вариант...

**Comment by maxcom** [comment]
Этот текст давно перенесен в исходники (см. https://github.com/maxcom/lorsource/blob/master/src/main/webapp/help/new-topic-forum.md). Опечатка там поправлена.

Баг закрою.
