### ISSUE TITLE
@useraname cast

### ISSUE THREAD

**Issue by yurikoles** [maxcom/lorsource#655]
Было бы не плохо сделать как в твиторе, гитхабе, слаке, фсб-уке, да и вообще в любом сайте возможность преобразовать @maxcom в [profile]maxcom[/profile].
Плюс к этому сделать возможность кастовать модераторов с помощью строки @moderators

**Comment by maxcom** [comment]
да, идея хорошая

**Comment by kloun** [comment]
вообще, Markdown вместо лоркода надо бы прикрутить... @maxcom когда начнешь?

**Comment by postman0** [comment]
Ни в коем случае не прикручивать.

**Comment by Werenter** [comment]
@maxcom закрой issue, неактуально же

**Comment by maxcom** [comment]
Да, реализовано в markdown. В lorcode не будет.
