### ISSUE TITLE
RSS pubDate time format

### ISSUE THREAD

**Issue by dim13** [maxcom/lorsource#674]
Согласно спецификации RSS 2.0 pubDate должен соответствовать RFC822.

Пример: Sat, 07 Sep 2002 0:00:01 GMT

Однако в данной реализации у дня месяца (здесь 07) не хватает нуля.

**Comment by maxcom** [comment]
rfc не требует наличия ведущего нуля у дня месяца

**Comment by dim13** [comment]
https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements

Хоть это явно и не описано, но в примере это есть.

**Comment by maxcom** [comment]
Явно это описано в rfc, читай его

суббота, 15 августа 2015 г. пользователь Dimitri Sokolyuk написал:
