### ISSUE TITLE
сломалась статистика сервера

### ISSUE THREAD

**Issue by kloun** [maxcom/lorsource#703]
404 пишет при заходе.

**Comment by kloun** [comment]
и да, как центос тебе? нравится?)

**Comment by maxcom** [comment]
мне centos 7 нравится гораздо больше, чем centos 6. А плане сравнения с Fedora я пока не очень заметил разницу.

**Comment by maxcom** [comment]
статистику поправим, эту часть еще не переносили

**Comment by kloun** [comment]
понял.

**Comment by kloun** [comment]
кстати, зачем время БД писать при каждом поисковом запросе? лишняя информация теперь уже, ИМХО. Вместо этого в логи надо бы, когда определенное число милисекунд превышает.
