### ISSUE TITLE
Обновить тестовую базу данных для создания локальной копии сайта

### ISSUE THREAD

**Issue by ghost** [maxcom/lorsource#705]
Сейчас после выполнения `mvn liquibase:update` валится с ошибкой:

`[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:2.0.1:update (default-cli) on project lor: Error setting up or running Liquibase: Migration failed for change set sql/updates/2014-10-27-timestamp-timezone.xml::2014102901::Maxim Valyanskiy:
[ERROR] Reason: liquibase.exception.DatabaseException: Error executing SQL GRANT SELECT ON TABLE jam_wiki_user TO jamwiki: ERROR: role "jamwiki" does not exist:
[ERROR] Caused By: Error executing SQL GRANT SELECT ON TABLE jam_wiki_user TO jamwiki: ERROR: role "jamwiki" does not exist:
[ERROR] Caused By: ERROR: role "jamwiki" does not exist
`

**Comment by maxcom** [comment]
сделай пользователя jamwiki, мне кажется это описано в инструкции

**Comment by getsmp** [comment]
В инструкции такого нет:[https://github.com/maxcom/lorsource/wiki/%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%BE%D1%82%D0%BB%D0%B0%D0%B4%D0%BE%D1%87%D0%BD%D0%BE%D0%B9-%D0%BA%D0%BE%D0%BF%D0%B8%D0%B8-%D1%81%D0%B0%D0%B9%D1%82%D0%B0#%D0%9D%D0%B0%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%91%D0%94](url)

Потому что убрано коммитом https://github.com/maxcom/lorsource/wiki/%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%BE%D1%82%D0%BB%D0%B0%D0%B4%D0%BE%D1%87%D0%BD%D0%BE%D0%B9-%D0%BA%D0%BE%D0%BF%D0%B8%D0%B8-%D1%81%D0%B0%D0%B9%D1%82%D0%B0/_compare/e062ee9d06544a4758bcbd955e6068d75a48cee1...196be17b5563def660adb63ceb897e489b054a93

Ревертни его, так как если применить то, что удалено, то сборка проходит.

**Comment by getsmp** [comment]
`mvn package jetty:run` пишет в лог вот [это](http://pastebin.com/6655zh6s) и на 127.0.0.1:8080 отдает Error 503.

**Comment by maxcom** [comment]
вернул jamwiki в описание. Про ошибку не знаю, выглядит страшно :-) У меня на нескольких разных компах все успешно работает, попробуй mvn clean и снова собрать.

**Comment by getsmp** [comment]
Не помогло.

**Comment by jollheef** [comment]
Разворачивал сегодня по руководство из Wiki на чистую систему. Проблем не было.

Вестимо задача уже не актуальна.
