### ISSUE TITLE
Можно выйти из профиля с помощью GET-запроса

### ISSUE THREAD

**Issue by smaximov** [maxcom/lorsource#712]
Переход по ссылке [/logout](https://www.linux.org.ru/logout) (или по [любой](https://goo.gl/stZwLh) ссылке, которая ведёт на /logout) приводит к завершению сессии.  То, что для [формы](https://github.com/maxcom/lorsource/blob/ad1a6c7ad0a767e854eaa02272f73a24e5279cfe/src/main/webapp/WEB-INF/jsp/whois.jsp#L50) указано `method="POST"`, по-видимому не помогает. Надо на сервере проверять, что ли.

**Comment by tenno-seremel** [comment]
Так логично, «переход по ссылке» и форма друг с другом никак не связаны, так что только на сервере и проверять.

**Comment by maxcom** [comment]
поправил
