### ISSUE TITLE
Удаление сообщения без удаления ветки

### ISSUE THREAD

**Issue by bodqhrohro** [maxcom/lorsource#723]
В правиле 7.1 форума Linux.org.ru указано, что удаляя нарушающее правила сообщение, модератор удаляет ответы на него по своему усмотрению. Однако технически возможность удаления сообщения без ветки обсуждения, похоже, так и не реализована. В связи с этим модераторы аргументируют откровенную избирательность в модерации тем, что удаление нарушающих правила сообщений, в том числе в старых и активных темах, наносит вред форуму из-за удаления целых веток. Поскольку конкретное сообщение может предоставлять пользу для посетителей и при этом нарушать правила, предлагаю как альтернативное решение разрешить модераторам цензурировать сообщения --- вырезать из них мат, провокации, оффтопик и т. д.; исправлять форматирование и правописание, как это делается на StackOverflow. Не вижу в этом проблемы, так как модерация прозрачна за счёт просмотра истории редактирования и удалённых сообщений активными регистрантами форума.

Также ввиду исторической особенности форума --- изменения темы дискуссии в ходе обсуждения --- нужен вынос веток обсуждения в отдельные топики. Это также послужит инструментом спасения адекватных подобсуждений в провокационных топиках.

**Comment by reverendhomer** [comment]
<offtop> А ты что, таки всё ещё есть в списке не забаненных регистрантов? О_о </offtop>

**Comment by bodqhrohro** [comment]
<offtop>Нет. Но я изучал локальную копию движка, в том числе с правами модератора.</offtop>

**Comment by mandala-mbwa** [comment]
Удаление ветки -- фича.

Удаление одного комментария разрушит нить дискуссии в нынешнем представлении комментариев -- придется оставлять сообщение с пометкой "удалено". Да даже в древовидном виде это выглядит безобразно.

**Comment by bodqhrohro** [comment]
На многих сайтах так и есть. Каждый комментарий ценен сам по себе, если явно не подпадает под 5.4, мало того — части удалённых комментариев могут содержаться в ответах на них. Недревовидное отображение дискуссий (нет ограничений на глубину комментирования) способствует развитию продолжительных обсуждений, в ходе которых постепенно меняется тема — и зачастую получается так, что не замеченный вовремя модераторами нарушающий правила комментарий при удалении потащит за собой в могилу практически не связанную с ним ветку обсуждения.

**Comment by Pinkbyte** [comment]
Собственно если удаленный комментарий процитирован дальше в ответах(а это случается гораздо чаще чем копипаста этого комментария в другую ветвь дискуссии), конкретно - та часть, из-за чего он удалён, что делать модератору? Идти по дереву комменту и выискивать? Забить?

По-моему идея мертворожденная

**Comment by bodqhrohro** [comment]
Чтоб не "выискивать", можно сделать отображение ответов на комментарий. Кажется, такую идею уже обсуждали и она упёрлась то ли в снижение эффективности кэширования, то ли в неактуальность данных до обновления страницы.

**Comment by mandala-mbwa** [comment]
> Собственно если удаленный комментарий процитирован дальше в ответах(а это случается гораздо чаще чем копипаста этого комментария в другую ветвь дискуссии), конкретно - та часть, из-за чего он удалён, что делать модератору? Идти по дереву комменту и выискивать? Забить?

Цитировать не разметкой, а ссылкой на внутреннее сообщение с параметром выведения в цитату только нужного  куска текста. При удалении цитата автоматом заменяется на сообщение от модератора с причиной удаления или на заглушку для анонимов и прочих, кто не может смотреть удаленные.  Этим же механизмом можно смотреть превьюшки ответов/родительских сообщений в ветке (чем сейчас занимается lorify).

Выводить всё это безобразие скриптами на стороне клиента, на то что цитаты сломаются у всяких маргиналов с отключенными скриптами и недобраузерами плевать! @bodqhrohro, пили патч, я буду за!

Кстати, за цитирование текстом внутренних сообщений надо будет строго карать! Иначе вся затея ломается.

**Comment by bodqhrohro** [comment]
> на то что цитаты сломаются у всяких маргиналов с отключенными скриптами и недобраузерами плевать
Не взлетит. Но можно проверять цитату и на бэкенде, выдавая ошибку, если она не находится в исходном сообщении. Однако тогда нужен отдельный тег для невнутренних цитат.

**Comment by olegchir** [comment]
Можно сделать фичу: модератор может удалять сообщение, только написав коротко и цензурно, о чем там было. Этим объяснением заменяется текст удаляемого комментария, комментарий выделяется темой (легко) и стилем комментария (хорошо но сложно).

**Comment by jollheef** [comment]
Дубль #770

Реализовано в #781
