### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kloun** [maxcom/lorsource#744]
можно удалять? в текущем виде это не годно к использованию...

**Comment by jollheef** [comment]
Транклюкировать бы!

**Comment by fedor-elizarov** [comment]
А где трагедия?

**Comment by fedor-elizarov** [comment]
@jollheef  
>kloun commented on 29 Nov 2016 
мля не заметил, но я думал ЛОРА Крофт ещё где то жива на стороне. А так норм держать иссульку открытой которую невозможно закрыть из за того что не существует объекта по поводу которого она открыта? ::)

**Comment by jollheef** [comment]
> А так норм держать иссульку открытой которую невозможно закрыть из за того что не существует объекта по поводу которого она открыта? ::)

Нет. Поэтому я и предложил её закрыть.

**Comment by fedor-elizarov** [comment]
@maxcom  Масёк, закрывай лавочку, нам наврали пирогов не будет ::) Но я так понимаю иссульки не закрываются в виду того что это как бы напоминалки, вроде не надо, но если что перед глазами, это как вот про векторные картинки ещё с 15го года висит.
