### ISSUE TITLE
[FR] возможность модераторам удалять только комментарий, а не всю ветвь

### ISSUE THREAD

**Issue by rekcuFniarB** [maxcom/lorsource#770]
Много лет на это жалуются, когда из-за формального нарушения в каком-то комменте удаляется полезная ветвь с полезным содержанием и полезными техническими ответами. При этом общавшиеся в ветви зачастую не в курсе что выше где-то есть "некорректный комментарий".

Вариантов реализации полно, например в таблице comments в поле «deleted» хранить не булево значение, а например 0, 1 и 2. 0 означает не удалено, 1 означеает удалена ветвь, 2 означает удалён единичный коммент. Если 2 то просто вместо содержимого комментария отображать текст «комментарий удалён». По-моему, всё просто.

Или если с этим какие-то сложности, можно более простой вариант: у модераторов кнопка «удалить без удаления ветви» просто одним кликом редактирует пост, заменяя содержимое на «комментарий удалён», можно с сохранением истории, история и так уже реализована при правках.

Одно из последних обсуждений: https://www.linux.org.ru/forum/linux-org-ru/13741076

**Comment by kloun** [comment]
я за.

**Comment by maxcom** [comment]
2-й вариант костыльный, но, скорее всего только он и реализуем без существенных переделок. В 1-м варианте будут сложности с трекером и другими выборками напрямую из 
таблицы comments.

**Comment by jollheef** [comment]
Реализовано в #781.
