### ISSUE TITLE
Ошибка на странице about.

### ISSUE THREAD

**Issue by yurikoles** [maxcom/lorsource#793]
https://www.linux.org.ru/about
>Защиту сайта от DDoS-атак осуществляет .

Так кто её осуществляет?

**Comment by bodqhrohro** [comment]
[УМВР](https://user-images.githubusercontent.com/2134486/43359211-413d18e0-92a7-11e8-980b-d962b87da951.png)

**Comment by yurikoles** [comment]
Да, видимо уже починили.
