### ISSUE TITLE
Собиратель «линков» в «теме»

### ISSUE THREAD

**Issue by zvezdochiot** [maxcom/lorsource#807]
Было бы совсем неплохо, если бы ЛОР-движок собирал внешние ссылки, прозвучавшие в «теме».

**Comment by jollheef** [comment]
Не совсем понятно, каким образом это будет делать тему содержательнее.

А каким образом ты это представляешь себе в интерфейсе?

**Comment by zvezdochiot** [comment]
Идёт текст "темы", за ним "Ссылки в теме:" и список собственно.

**Comment by jollheef** [comment]
> Идёт текст "темы", за ним "Ссылки в теме:" и список собственно.

А каким образом это может сделать тему содержательнее?

В чем смысл оторванных от контекста ссылок?

**Comment by zvezdochiot** [comment]
>А каким образом это может сделать тему содержательнее?

Внешние ссылки - наибелее информативная часть ЛОРа. Это как оглавлене в начале книги.

**Comment by zvezdochiot** [comment]
Если возникает сомнение по администрированию списка ссылок, так можно ссылки собирать по "белому" списку: git, sf и еже.

**Comment by zvezdochiot** [comment]
Как это "выглядит"? Ну как-то так:

https://www.linux.org.ru/forum/lor-source/14581227
