### ISSUE TITLE
RFE: поддержка Markdown (Pandoc Markdown) для разметки сообщений

### ISSUE THREAD

**Issue by intelfx** [maxcom/lorsource#808]
LORCODE многословен и неудобен. Также, текущая реализация LORCODE имеет несколько неприятных особенностей (например, `>`-цитаты заменяются на `[quote]...[/quote]` в исходнике), затрудняющих редактирование.

Реквестируется поддержка Markdown (лучше, если это будет один из расширенных диалектов Markdown, как [Pandoc Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown)) в качестве альтернативного языка разметки сообщений. При этом:

- [ ] исходный текст сообщения должен сохраняться без изменений (а не преобразовываться в LORCODE или любое другое IR) для удобства редактирования;
- [ ] было бы неплохо реализовать расширение для упоминания пользователей через `@`.

**Comment by bvn13** [comment]
я занялся прикруткой

**Comment by intelfx** [comment]
Класс.

Если бросишь на полпути, пни, я допилю — просто я хз, где начинать. Запутался в этих джавовских ControllerFactoryFactory.

**Comment by bvn13** [comment]
пока все понятно

**Comment by bvn13** [comment]
где у нас встречается редактирование сообщений? создание темы/новости (галерею не проверил еще, кстати), комментирование - еще где?

**Comment by bvn13** [comment]
@maxcom тестами обязательно покрывать?

**Comment by bvn13** [comment]
и сейчас тесты проходят?

**Comment by maxcom** [comment]
Минимальные тесты нужны; сейчас все тесты проходят.

Да, там в исходниках уже есть один рендерер markdown, хорошо бы его выпилить и заменить на flexmark-java.

**Comment by maxcom** [comment]
Тесты проходят, в том числе автоматически на каждый костит.

Парсер называется pegdown, поищи его по импортам

пт, 16 нояб. 2018 г. в 10:21, Vyacheslav N. Boyko <notifications@github.com

**Comment by bvn13** [comment]
@maxcom можно закрывать
