### ISSUE TITLE
Нельзя заблокировать аккаунт без "передачи сообщений специальному пользователю"

### ISSUE THREAD

**Issue by rekcuFniarB** [maxcom/lorsource#861]
![скриншот](https://i.imgur.com/NxhGQdY.png)

Зачем тогда две галки, если обе обязательны? Форма намекает что можно удалиться без передачи сообщений аккаунту "Deleted". Выглядит как баг.

 А если так и задумано, то лишняя галка ни к чему, только вводит в заблуждение. Точнее. если так и задумано, то там две галки лишние, достаточно согласия.

Но раз всё равно можно удаляться, было бы неплохо иметь и опцию без анонимизации сообщений.

**Comment by fedor-elizarov** [comment]
@rekcuFniarB  закрой, протухло
