### ISSUE TITLE
Баг в маркдауне: при рендере блока кода съедается первая строка

### ISSUE THREAD

**Issue by bvn13** [maxcom/lorsource#878]
Описал с примерами тут: https://www.linux.org.ru/forum/linux-org-ru/15211379

Я понимаю, что первая строка воспринимается в поломанном случае как язык разметки. Но, может быть, есть возможность, если она (кодировка) не определена, то рассматривать первую строку как строку кода, а не язык кода?

**Comment by bvn13** [comment]
Может быть, надо так: если нет пробельного символа в первой строке - то это язык кода, если есть - то простая строка.

**Comment by yurikoles** [comment]
ФичаКостыльБезногим. Попробуй тут даже так написать, в сайте-эталоне маркДауна

**Comment by maxcom** [comment]
не баг, markdown в других реализациях так же работает
