### ISSUE TITLE
Седалища полуобнажённыя

### ISSUE THREAD

**Issue by bodqhrohro** [maxcom/lorsource#885]
Не соблаговолит ли великий государь всея ЛОРа устранить срам сей с очей достопочтенных посетителей, доходов рекламных сайты не лишающих?

![2019-12-10-004309_1366x768_scrot](https://user-images.githubusercontent.com/2134486/70479601-65be6c00-1ae6-11ea-948f-733439a6f57d.png)

**Comment by bodqhrohro** [comment]
Опять.
![2019-12-10-212731_1366x768_scrot](https://user-images.githubusercontent.com/2134486/70561874-f0a97000-1b93-11ea-8952-cd711d0ed1a1.png)

**Comment by maxcom** [comment]
Отключил большие баннеры, надеюсь вместе с ними уйдет и эта реклама.

Напиши plz если еще раз вылезет что-то такое.

**Comment by bodqhrohro** [comment]
Теперь то же самое, но маленькое.
![2019-12-10-222307_1366x768_scrot](https://user-images.githubusercontent.com/2134486/70565924-c360c000-1b9b-11ea-84f8-3c1474f870cf.png)

**Comment by bodqhrohro** [comment]
Да нет, и большие лезут. Оно точно выключено уже? :3

**Comment by bodqhrohro** [comment]
Опять жопы.
![2022-04-14-002442_1366x768_scrot](https://user-images.githubusercontent.com/2134486/163274535-678de01a-fc41-417d-b9e5-54e6038f3c4b.png)
