### ISSUE TITLE
Едет верстка с горизонтальной прокруткой

### ISSUE THREAD

**Issue by kergalym** [maxcom/lorsource#888]
Например, тут: https://www.linux.org.ru/forum/development/15474379

![C1Q39hG](https://user-images.githubusercontent.com/9489149/72656009-b2894280-39c2-11ea-8d77-2155b6446dc1.png)

Воспроизводится если указать ID коммента в адресной строке или перейти по ссылке: https://www.linux.org.ru/forum/development/15474379?cid=15474681

Firefox 72.0.1

**Comment by outZoNe** [comment]
похоже виноват этот коммент: https://www.linux.org.ru/forum/development/15474379?cid=15474701

**Comment by outZoNe** [comment]
Нужно у тега code удалить стиль: `white-space: pre;`
