### ISSUE TITLE
FR: менструальный календарь постинга

### ISSUE THREAD

**Issue by bodqhrohro** [maxcom/lorsource#985]
Некоторые пользователи ЛОРа испытывают месячные. [Даже если у них нет яичников и матки.](https://curvyandtrans.com/p/C4BD87/cycle-dynamics/)

В связи с этим, целесообразно добавить в профиле настройки фазы и периодичности менструального цикла, и автоматически замораживать постинг на время ПМС.

Для пользователей, которые также являются корректорами и/или модераторами, может быть целесообразно также ограничение только этих полномочий без замораживания постинга по отдельной опции.

**Comment by Pinkbyte** [comment]
Я конечно дико извиняюсь, но у меня при чтении сего feature request была такая же реакция, как от этого видео: https://www.youtube.com/watch?v=TVwvcGajoQg

**Comment by bodqhrohro** [comment]
О @megabaks‍-то помнишь ещё? :P

**Comment by bodqhrohro** [comment]
А впрочем, я уж и не помню, откуда эти россказни про ПМС у Мегабакса, единственное упоминание в поиске за моим авторством, внезапно. Может, false memory?

**Comment by megabaks** [comment]
А!? Чо!?
Голоса из прошлой жизни!?

**Comment by bodqhrohro** [comment]
@megabaks угу.

Правду про тебя на лурке пишут, кстати?

**Comment by megabaks** [comment]
Понятия не имею: не читал.

**Comment by megabaks** [comment]
Похоже на правду

**Comment by ozz-is-here** [comment]
Серьёзный форум такой серьёзный

**Comment by bodqhrohro** [comment]
А ты мастер выдумывать утверждения и тут же их опровергать.

**Comment by ozz-is-here** [comment]
Ничего не выдумывал и ничего не опровергал. Prove me wrong.

**Comment by bodqhrohro** [comment]
А откуда тогда эти мантры про серьёзный форум?

**Comment by bodqhrohro** [comment]
> as completed

протестую

Где номер коммита?

**Comment by maxcom** [comment]
В GitHub нет поля resolution, только один вариант закрытия issue.

Ср, 22 июня 2022 г. в 01:58, bodqhrohro ***@***.***>:

**Comment by xaizek** [comment]
> В GitHub нет поля resolution, только один вариант закрытия issue.

Если нажать на стрелочку, то там есть второй вариант с недавнего времени.
