### ISSUE TITLE
Сброс пароля - баг или фича?

### ISSUE THREAD

**Issue by FeelUsM** [maxcom/lorsource#996]
Я забыл пароль, запрашиваю новый, и мне создают новый пароль типа `+sBg;*DS(&lt;`, всегда (я всего 2 пароля проверил) асодержащий `&lt;`.
Ну хорошо, я немного опытный, я догадался, что `&lt;` надо заменить на `<`.
А как же остальные менее опытные?

**Comment by maxcom** [comment]
thanx, что-то я недавно разломал
