### ISSUE TITLE
Парсер ссылок некорректно обрабатывает @ в них.

### ISSUE THREAD

**Issue by EXL** [maxcom/lorsource#997]
Рендеринг Markdown.

Нужно где-то в кастомном расширении Markdown, которое отвечает за каст пользователя как-то игнорировать ссылки, либо расставить приоритеты для парсера таким образом, чтобы ссылки не летели в это расширение.

![image](https://user-images.githubusercontent.com/232116/166504834-c87824c1-f95b-4b79-897e-183ebb7971ab.png)

Пример ошибки [по ссылке](https://www.linux.org.ru/forum/general/16859999?cid=16860095).

**Comment by alex0x08** [comment]
Должно было починиться вот этим [пул-реквестом](https://github.com/maxcom/lorsource/pull/1042).
