### ISSUE TITLE
После удаления аватара, не могу загрузить новый

### ISSUE THREAD

**Issue by KitsuneSolar** [maxcom/lorsource#999]
Здравствуйте!

После того, как я удалил аватару, я больше не могу поставить новую.

![2022-05-22 17 32 03 www linux org ru 2c145965ed0f](https://user-images.githubusercontent.com/12877339/169700540-9f44d6ff-34aa-4e14-a558-4085c58eae92.png)

При нажатии на кнопку "Изменить", появляется следующая ошибка:

![2022-05-22 17 33 23 www linux org ru d29805035ea4](https://user-images.githubusercontent.com/12877339/169700567-1cd6ab2a-b471-469a-b3ab-a159006ec647.png)

## UPD
Увидел тему: https://www.linux.org.ru/forum/linux-org-ru/16872117

**Comment by KitsuneSolar** [comment]
UPD
Увидел тему: https://www.linux.org.ru/forum/linux-org-ru/16872117.

**Comment by maxcom** [comment]
https://www.linux.org.ru/forum/linux-org-ru/16897845
